[package]
name = "scriptkiddie-parser"
edition = "2021"
version.workspace = true
authors.workspace = true

[dependencies]
scriptkiddie-lexer = { path = "../scriptkiddie-lexer"}
thiserror = "1.0.64"

[lints]
workspace = true
